--- 
title: "AI Tools in the Job Recruiting Process"
author: "Jingyi (Vera) Wang, Kuigang (KG) Zhang, Michael Czapp, Xinqian (Demi) Dai, Yousuf Altameemi"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Introduction to Our Book

For students at the Stephen M. Ross School of Business, the primary goal by graduation is to have a full-time job offer at a company and location that makes them excited to start their professional careers. Throughout the fall and winter semesters, recruiting is an incredibly time-consuming and stressful process, so students must use their time and effort efficiently to maximize their job opportunities. However, the recent and rapid progression of artificial intelligence (AI) tools has reshaped the recruiting landscape. Therefore, students need to understand how they can use these tools to their advantage and how recruiters may be using AI throughout the recruitment process.

Our book will provide a comprehensive overview of these AI tools. We will approach this from two perspectives: students’ and recruiters’. For students, we discuss how they can use AI job finders, resume and cover letter optimization, practice interviews, and automated applications to support their professional endeavors. On the other hand, we discuss what AI tools recruiters may use, like applicant tracking systems (ATS), resume and cover letter screening, interview assessments, skill assessments, and predictive analytics. Then, we suggest how students should tailor their presentation of themselves to fit what these AI tools look for.

